### ISSUE TITLE
Error on python3.8

### ISSUE THREAD

**Issue by bonelifer** [davidschlachter/firefly-iii-email-summary#2]
```
✖ python3.8 monthly-report.py 
Traceback (most recent call last):
  File "/home/william/.local/lib/python3.8/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "/home/william/.local/lib/python3.8/site-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/home/william/.local/lib/python3.8/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/home/william/.local/lib/python3.8/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "monthly-report.py", line 137, in <module>
    main()
  File "monthly-report.py", line 41, in main
    categories = s.get(url).json()
  File "/home/william/.local/lib/python3.8/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by davidschlachter** [comment]
The `JSONDecodeError: Expecting value` error suggests that this is an authentication issue, since `firefly-iii` is sending an empty response.
