### ISSUE TITLE
"json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)"

### ISSUE THREAD

**Issue by super-ben** [davidschlachter/firefly-iii-email-summary#3]
I've encountered an error while running the monthly report script - namely, I didn't receive one. 😄 Once I realized, I ran it manually and saw the following:

"Traceback (most recent call last):
  File "/home/username/.local/lib/python3.10/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/username/firefly-iii-email-summary-main/monthly-report.py", line 158, in <module>
    main()
  File "/home/username/firefly-iii-email-summary-main/monthly-report.py", line 42, in main
    categories = s.get(url).json()
  File "/home/username/.local/lib/python3.10/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)"

It seems to me, something broke but woudn't know why - I didn't manually change anything on the server regarding the Python environment, and when I look at /home/username/.local/lib/python3.10/site-packages/, all modules were changed in last October, so it is rather strange. On a whim, I updated "requests" package, so now I have the following:

"pip3 list |grep requests
requests               2.28.1"

(before and after upgrading the module, the error message remained the same)

Do you have any ideas on how to restore functionality? I suspect something changed in Firefly 5.7.17.

**Comment by super-ben** [comment]
Solved: I generated a new access token in Firefly III and the reporting works again. I had no idea that access tokens "expire", but will keep them in mind. :)

**Comment by super-ben** [comment]
Solved: I generated a new access token in Firefly III and the reporting works again. I had no idea that access tokens "expire", but will keep them in mind. :)
